### ISSUE TITLE
希望增加群记事功能和图片记事功能

### ISSUE THREAD

**Issue by newcovid** [Passerby-D/nonebot_plugin_note#10]
希望可以增加在群里发送提醒的功能和可以记录图片记事的功能

**Comment by Passerby-D** [comment]
感谢提议，前段时间一直在忙大作业，最近才闲下来（

已更新群记事功能
图片记事功能后续应该会考虑添加

**Comment by newcovid** [comment]
更新后报错,忘了记录了,在代码里改了颜色和字体后重启报错,定时推送也失效了,但是记事帮助还能用
重启时报错:
01-15 14:07:38 [ERROR] apscheduler | Job "_restart (trigger: interval[0:00:05], next run at: 2023-01-15 14:07:43 CST)" raised an exception
Traceback (most recent call last):
  File "/root/training/Python-3.9.10/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/training/Python-3.9.10/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/root/training/Python-3.9.10/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/nonebot_plugin_note/__init__.py", line 1052, in _restart
    info=await nonebot.get_bot().call_api("get_group_info",group_id=group_id)
  File "/root/training/Python-3.9.10/lib/python3.9/site-packages/nonebot/__init__.py", line 158, in get_bot
    raise ValueError("There are no bots to get.")
ValueError: There are no bots to get.

**Comment by Passerby-D** [comment]
奥 好像是之前的一个小bug
我好像光在github上改了 忘了到pypi上改了（草
你再更新试试呢
