### ISSUE TITLE
部分系统环境下字体缺少问题，希望可以加入自动检查并安装字体的功能

### ISSUE THREAD

**Issue by Nranphy** [Passerby-D/nonebot_plugin_note#11]
在服务器的 Debian 11 下运行发生以下错误：
```
03-22 14:58:53 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_note) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/var/mybot/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/var/mybot/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot_plugin_note/__init__.py", line 1200, in _
    await CreateMutiLinesPic(notes,30,r"{}\data\list.png".format(cur_dir))
  File "/var/mybot/.venv/lib/python3.9/site-packages/nonebot_plugin_note/__init__.py", line 1573, in CreateMutiLinesPic
    font = ImageFont.truetype(font_conf['type'],font_conf['size'])
  File "/var/mybot/.venv/lib/python3.9/site-packages/PIL/ImageFont.py", line 1008, in truetype
    return freetype(font)
  File "/var/mybot/.venv/lib/python3.9/site-packages/PIL/ImageFont.py", line 1005, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/var/mybot/.venv/lib/python3.9/site-packages/PIL/ImageFont.py", line 255, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```
~~**个人感觉对于用户的比较干净的解决方案**~~
查看代码发现使用字体为`simkai.ttf`，将 windows 的楷书字体文件放入服务器的`/usr/share/fonts/truetype/`目录下，再测试功能即可

**小建议**
希望可以加入自动检查并安装字体的功能（记得meetwq佬的petpet插件有类似的实现或者readme有解决方法，[这里](https://github.com/noneplugin/nonebot-plugin-imageutils)，感觉可以参考）
代码都写在一个文件里了，感觉要修改好痛苦，放弃pr了。。×

**Comment by Passerby-D** [comment]
hhhhhh我代码确实写的很屎山
谢谢大佬的建议

**Comment by Nranphy** [comment]
不是大佬不是大佬
![害怕捏](https://i.328888.xyz/2023/04/19/iFGq3c.jpeg)
加油！！插件超方便的！
