### ISSUE TITLE
nb2.0.0b5、nonebot_plugin_apscheduler0.2.0兼容性问题

### ISSUE THREAD

**Issue by Ikaros-521** [Passerby-D/nonebot_plugin_note#9]
相关版本：
nonebot2 = 2.0.0b5
nonebot_plugin_note = 0.2.0
nonebot-plugin-apscheduler = 0.2.0

报错内容：
```
12-11 18:23:41 [ERROR] nonebot | Failed to import "nonebot_plugin_note"
Traceback (most recent call last):
  File "/usr/local/python3/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/LX_Bot/./bot.py", line 32, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_note/__init__.py", line 481, in <module>
    @timing.scheduled_job("interval",seconds = 5,id='restart')
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/export.py", line 38, in __call__
    self[func.__name__] = func
AttributeError: 'str' object has no attribute '__name__'

```

**Comment by Ikaros-521** [comment]
解决方案：
注释 第10行左右的
`#timing = require("nonebot_plugin_apscheduler").scheduler`
修改第481行左右的timing为scheduler
```
#@timing.scheduled_job("interval",seconds = 5,id='restart')
@scheduler.scheduled_job("interval",seconds = 5,id='restart')
```
修改第489行左右的timing为scheduler
```
#timing.remove_job(job_id='restart')
scheduler.remove_job(job_id='restart')
```

**Comment by Passerby-D** [comment]
感谢大佬指正，已修改
